TestPaySignService22222:
    TestDb:
        TestLogsConnString:
            settings-key: TestLogsConnStringValue
            types:
                - Tag
                - RabbitMq
                - Logs
                - AzureBlobStorage
                - Optional
                - Manual

        TestLogsConnString2:
            settings-key: TestLogsConnStringValue2
            types:
                - AzureTableStorage
                - Optional
                
        TestStringConstant: "TestConstantName"
        
        TestNumberConstant: 8
    
    TestDb2:
        TestLogsConnString:
            settings-key: TestLogsConnStringValue
            types:
                - AzureBlobStorage
    
    TestJson:
        TestJsonProperty:
            settings-key: TestJsonKey
            types:
                - Json

        TestJsonArrayProperty:
            settings-key: TestJsonArrayKey
            types:
                - JsonArray
                
        TestJsonArrayProperty2:
            settings-key: TestJsonArrayKey2
            types:
                - JsonArray
    
    TestDb3:
        TestLogsConnString:
            settings-key: TestLogsConnStringValue3
            types:
                - MongoDB
    TestDb4:
        TestLogsConnString:
            settings-key: TestLogsConnStringValue
            types:
                - MongoDB

TestCandleHistoryServiceClient:
    TestServiceUrl:
        settings-key: TestCandleHistoryServiceUriValue
        types:
            - Redis

TestDutchAuctionClient:
    TestServiceUrl:
        settings-key: TestDutchAuctionServiceUriValue

TestMarketProfileServiceClient:
    TestServiceUrl:
        settings-key: TestMarketProfileServiceUriValue
